---
title: "CONSIGN: GAIA Curation. Part V"
author: "Francisco Sanchez-Saez"
date: "last-modified" 
editor: source
format:
  html:
    toc: true
    toc-location: left
    theme: cerulean
    css: style.css
    embed-resources: true
    number-sections: true
---

```{r}
#| echo: false
source("_common.R")
knitr::opts_chunk$set(
  eval = FALSE
)

```

```{r }
#| eval: true
#| include: false
# load libraries and functions------------------------------------------------
source(file.path("..", "scripts", "Librerias.R"))
source(file.path("..", "scripts", "Funciones.R"))

```

```{css, echo = FALSE}
.output {
max-height: 500px;
overflow-y: scroll;
}
```

# Load and clean bases

```{r}
# load pathes----------------------------------------------------------------
path_origenes_consign <- file.path( "r:", "CONSIGN_SD2270", 
                                    "1-DATOS", "1-BRUTOS")

procesados <- file.path( "r:", "CERES2", "CONSIGN_SD2270", 
                         "1-DATOS", "3-PROCESADOS")

```

```{r}
# read gaia_clinical_drugs5--------------------------------------------------
gaia_clinical_drugs5 <- fread(file.path("Resultados", "gaia_masters",
                          "gaia_clinical_drugs5.csv"), encoding = "Latin-1")

gaia_usagi <- fread(file.path("Resultados", "gaia_masters", "usagi",
                              "gaia_usagi.csv"))

```

```{r}
# load concepts vocabulary---------------------------------------------------
concepts_vocabulary <- fread(file.path("..", "EHDEN",
  "Vocabularies", "CONCEPT.csv"))
concepts_relationship <- fread(file.path("..", "EHDEN",
  "Vocabularies", "CONCEPT_RELATIONSHIP.csv"))
concepts_ancestor <- fread(file.path("..", "EHDEN",
  "Vocabularies", "CONCEPT_ANCESTOR.csv"))

```

# Create file to use with usagi

```{r}
# observe Clinical Drug format-----------------------------------------------
concepts_vocabulary |> filter(concept_class_id == "Clinical Drug Box")

# observe gaia_usagi
gaia_usagi

```

In this step, the USAGI tool is used to map the *pres_farma_cod* into standard concepts.

```{r}
#| include: false
# copy .qmd to CERES---------------------------------------------------------
unlink(file.path("r:", "CONSIGN_SD2270", "2-SCRIPTS", "R",
                 "1_07_7_GAIA_USAGI_mapping_CONSIGN.qmd"))
file.copy(from = file.path("1_07_7_GAIA_USAGI_mapping_CONSIGN.qmd"),
          to = file.path("r:", "CONSIGN_SD2270",
                         "2-SCRIPTS", "R"))

```

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>
